package com.rural.visual.entidades;

import com.rural.model.Associado;
import com.rural.persistence.dao.GenericDAO;
import com.rural.reports.AssociadosReport;
import com.rural.uteis.ConversorPersonalizado;
import com.rural.uteis.Formatos;
import com.rural.uteis.ValidatorUtil;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class jIFAssociado extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIFAssociado
     */
    public jIFAssociado() {
        initComponents();
        limparCampos();
        
        try {
            setFormatos();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDocumentacao = new javax.swing.JTabbedPane();
        jPDadosPessoais = new javax.swing.JPanel();
        jTFFiliacao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFTFNascimento = new javax.swing.JFormattedTextField();
        jTFNaturalidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCBEstadoCivil = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFConjuge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFGrauInstrucao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTFEnderecoResidencial = new javax.swing.JTextField();
        jTFBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTFMunicipio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCBUF = new javax.swing.JComboBox<>();
        jTFTelefone = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTFFiliacaoPai = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTFRG = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTFOrgExpeditor = new javax.swing.JTextField();
        jFTFDataExpedicaoRG = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFSerie = new javax.swing.JTextField();
        jTFCtps = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTFCertidaoNascimentoCasamento = new javax.swing.JTextField();
        jFTFCPF = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jTFTituloEleitor = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTFZona = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTFSecao = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTFNumeroBeneficio = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTFEspecie = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTFNit = new javax.swing.JTextField();
        jTFSttr = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jFTFDataTransferencia = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        jFTFExpedicaoCart = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPDadosProfissionais = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTFProfissao = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTFTamanhoPropriedade = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTFAreaUtilizada = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTFIncra = new javax.swing.JTextField();
        jTFEnderecoProfissao = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jCBUfProfissao = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jFTFDataPropria = new javax.swing.JFormattedTextField();
        jLabel47 = new javax.swing.JLabel();
        jTFMunicipioProfissao = new javax.swing.JTextField();
        jCBRegimeAtividade = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jTFNomeProprietario = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTFEmpresaPropriedade = new javax.swing.JTextField();
        jPDependentes = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jBCarteiraReport = new javax.swing.JButton();
        jBPesquisa = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFMatriculaAnterior = new javax.swing.JTextField();
        jFTFDataAdmissao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTFApelido = new javax.swing.JTextField();
        jCBSexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jFTFDataRecadastramento = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Associado");

        jPDocumentacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPDocumentacao.setAutoscrolls(true);
        jPDocumentacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPDocumentacao.setPreferredSize(getPreferredSize());

        jPDadosPessoais.setPreferredSize(new java.awt.Dimension(1063, 400));

        jTFFiliacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Filiação - Mãe");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nascimento");

        jFTFNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFNascimentoFocusLost(evt);
            }
        });

        jTFNaturalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Naturalidade");

        jCBEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTEIRO", "ESTAVEL", "CASADO", "DIVORCIADO", "VIUVO" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Estado Civil");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nome do Conjuge/Companheiro(a)");

        jTFConjuge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Grau de Instrução");

        jTFGrauInstrucao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Endereço Residencial");

        jTFEnderecoResidencial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Bairro/Comunidade");

        jTFMunicipio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Município");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("UF");

        jCBUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RN", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCBUF.setToolTipText("");

        jTFTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Telefone");

        jTFEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Email");

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel62.setText("Filiação - Pai");

        jTFFiliacaoPai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPDadosPessoaisLayout = new javax.swing.GroupLayout(jPDadosPessoais);
        jPDadosPessoais.setLayout(jPDadosPessoaisLayout);
        jPDadosPessoaisLayout.setHorizontalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFFiliacaoPai)
                    .addComponent(jTFFiliacao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEnderecoResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTFBairro)))
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCBUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmail))
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel62)
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFTFNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jTFGrauInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel20))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTFConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPDadosPessoaisLayout.setVerticalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFiliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFiliacaoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFGrauInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFEnderecoResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPDocumentacao.addTab("Dados Pessoais", jPDadosPessoais);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("CPF");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("RG");

        jTFRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Org. Expeditor");

        jTFOrgExpeditor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFTFDataExpedicaoRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFDataExpedicaoRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDataExpedicaoRGFocusLost(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Data Expedição");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("CTPS");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Série");

        jTFSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFCtps.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Certidão de Nascimento ou Casamento (Livro/Folha)");

        jTFCertidaoNascimentoCasamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFTFCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Título de Eleitor");

        jTFTituloEleitor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Zona");

        jTFZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Seção");

        jTFSecao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Número do Benefício");

        jTFNumeroBeneficio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Espécie");

        jTFEspecie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("NIT");

        jTFNit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFSttr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Transferência do STTR");

        jFTFDataTransferencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFDataTransferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDataTransferenciaFocusLost(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Data de Transferência");

        jFTFExpedicaoCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Expedição Carteira");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jTFNumeroBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jTFEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel34))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTFNit)
                                        .addGap(316, 316, 316))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jLabel35)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jTFRG, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFOrgExpeditor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jFTFDataExpedicaoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTFCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFSerie)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFSttr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFDataTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCertidaoNascimentoCasamento)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jFTFExpedicaoCart, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jTFTituloEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jTFZona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jTFSecao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFOrgExpeditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFDataExpedicaoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCertidaoNascimentoCasamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFTituloEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNumeroBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSttr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDataTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFExpedicaoCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPDocumentacao.addTab("Documentação", jPanel2);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Profissão");

        jTFProfissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Regime de Atividade");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Tamanho Propriedade");

        jTFTamanhoPropriedade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Área Utilizada");

        jTFAreaUtilizada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("INCRA");

        jTFIncra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFEnderecoProfissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Endereço de trabalho");

        jCBUfProfissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBUfProfissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RN", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("UF");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Desde");

        jFTFDataPropria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFDataPropria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDataPropriaFocusLost(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Município");

        jTFMunicipioProfissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCBRegimeAtividade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBRegimeAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ECONOMIA_FAMILIAR", "ASSALARIADO", "PROPRIETARIO", "MEEIRO", "PARCEIRO", "ARRENDATARIO", "COMODATARIO", "ASSENTADO", "POSSEIRO", "OUTROS" }));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Nome Proprietário");

        jTFNomeProprietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Empresa");

        jTFEmpresaPropriedade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPDadosProfissionaisLayout = new javax.swing.GroupLayout(jPDadosProfissionais);
        jPDadosProfissionais.setLayout(jPDadosProfissionaisLayout);
        jPDadosProfissionaisLayout.setHorizontalGroup(
            jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                        .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jTFTamanhoPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(jTFAreaUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(0, 186, Short.MAX_VALUE))
                                    .addComponent(jTFIncra)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosProfissionaisLayout.createSequentialGroup()
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addGap(0, 436, Short.MAX_VALUE))
                                    .addComponent(jTFProfissao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(98, 98, 98))
                                    .addComponent(jCBRegimeAtividade, 0, 225, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))
                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(611, 611, 611))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosProfissionaisLayout.createSequentialGroup()
                        .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFEmpresaPropriedade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeProprietario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEnderecoProfissao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDadosProfissionaisLayout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(488, 590, Short.MAX_VALUE))
                            .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTFMunicipioProfissao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel46))
                                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                                        .addComponent(jCBUfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFTFDataPropria, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPDadosProfissionaisLayout.setVerticalGroup(
            jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBRegimeAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTamanhoPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDadosProfissionaisLayout.createSequentialGroup()
                        .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFAreaUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFIncra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEmpresaPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEnderecoProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel45)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFMunicipioProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBUfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDataPropria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPDocumentacao.addTab("Dados Profissionais", jPDadosProfissionais);

        jPDependentes.setPreferredSize(new java.awt.Dimension(200, 550));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Nome");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Parentesco");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Nascimento");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("jButton2");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPDependentesLayout = new javax.swing.GroupLayout(jPDependentes);
        jPDependentes.setLayout(jPDependentesLayout);
        jPDependentesLayout.setHorizontalGroup(
            jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDependentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPDependentesLayout.createSequentialGroup()
                        .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addGroup(jPDependentesLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(0, 164, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDependentesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPDependentesLayout.setVerticalGroup(
            jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDependentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDependentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPDocumentacao.addTab("Dependentes", jPDependentes);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Excluir");

        jBCarteiraReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCarteiraReport.setText("Carteira");
        jBCarteiraReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCarteiraReportActionPerformed(evt);
            }
        });

        jBPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBPesquisa.setText("Pesquisa");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jBSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Matrícula");

        jTFMatricula.setEditable(false);
        jTFMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFMatricula.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Matrícula Anterior");

        jTFMatriculaAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFTFDataAdmissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFDataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDataAdmissaoFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data Admissão");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nome");

        jTFNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Apelido");

        jTFApelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCBSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sexo");

        jFTFDataRecadastramento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFDataRecadastramento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDataRecadastramentoFocusLost(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Data Recad.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisa)
                .addGap(2, 2, 2)
                .addComponent(jBCarteiraReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jFTFDataRecadastramento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFMatriculaAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFTFDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFApelido))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBSexo, 0, 1, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPDocumentacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFTFDataRecadastramento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFMatriculaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFTFDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPDocumentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(jBPesquisa)
                    .addComponent(jBCarteiraReport)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        if (!validateCamposCadastro()) {
            return;
        }

        Associado asso = associado;
        GenericDAO dao = new GenericDAO();

// <editor-fold defaultstate="collapsed" desc="Dados Pessoais">
        //asso.setMatricula(jTFMatricula.getText());
        try {
            asso.setDataExpedicao(ConversorPersonalizado.convertStringToDate(jFTFExpedicaoCart.getText()));
            asso.setDataNascimento(ConversorPersonalizado.convertStringToDate(jFTFNascimento.getText()));
            asso.setDataAdmissao(ConversorPersonalizado.convertStringToDate(jFTFDataAdmissao.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(jIFAssociado.class.getName()).log(Level.SEVERE, null, ex);
        }

        asso.setMatriculaAnterior(jTFMatriculaAnterior.getText());
        asso.setNome(jTFNome.getText());
        asso.setApelido(jTFApelido.getText());
        asso.setSexo(ConversorPersonalizado.convertStringToSexo(jCBSexo.getSelectedItem().toString())); // usar enum
        asso.setFiliacaoMae(jTFFiliacao.getText());
        asso.setFiliacaoPai(jTFFiliacaoPai.getText());
        asso.setNaturalidade(jTFNaturalidade.getText());
        asso.setEstadoCivil(ConversorPersonalizado.convertStringToEstadoCivil(jCBEstadoCivil.getSelectedItem().toString()));
        asso.setConjuge(jTFConjuge.getText());
        asso.setGrauInstrucao(jTFGrauInstrucao.getText());
        asso.setEndereco(jTFEnderecoResidencial.getText());
        asso.setBairro(jTFBairro.getText());
        asso.setCidade(jTFMunicipio.getText());
        asso.setUf(ConversorPersonalizado.convertStringToUF(jCBUF.getSelectedItem().toString()));
        asso.setTelefone(jTFTelefone.getText());
        asso.setEmail(jTFEmail.getText());
// </editor-fold>

// <editor-fold defaultstate="collapsed" desc="Documentação">
        asso.setCpf(jFTFCPF.getText());
        asso.setRg(jTFRG.getText());
        asso.setOrgaoExpedidor(jTFOrgExpeditor.getText());
        try {
            asso.setDataExpedicaoRG(ConversorPersonalizado.convertStringToDate(jFTFDataExpedicaoRG.getText()));
            asso.setDataRecadastramento(ConversorPersonalizado.convertStringToDate(jFTFDataRecadastramento.getText()));
            asso.setDataTransferenciaSTTR(ConversorPersonalizado.convertStringToDate(jFTFDataTransferencia.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(jIFAssociado.class.getName()).log(Level.SEVERE, null, ex);
        }
        asso.setCtps(jTFCtps.getText());
        asso.setSerieCtps(jTFSerie.getText());
        asso.setCertidaoNascimentoCasamento(jTFCertidaoNascimentoCasamento.getText());
        asso.setTituloEleitor(jTFTituloEleitor.getText());
        asso.setZonaEleitoral(jTFZona.getText());
        asso.setSecaoEleitoral(jTFSecao.getText());
        asso.setNumeroBeneficio(jTFNumeroBeneficio.getText());
        asso.setEspecieBeneficio(jTFEspecie.getText());
        asso.setNit(jTFNit.getText());
        asso.setTransferidoSTTR(jTFSttr.getText());


// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="Dados Profissionais">
        asso.setProfissao(jTFProfissao.getText());
        asso.setEmpresaPropriedade(jTFEmpresaPropriedade.getText());
        asso.setRegimeAtividade(ConversorPersonalizado.convertStringToRegimeAtividade(jCBRegimeAtividade.getSelectedItem().toString()));
        asso.setTamanhoPropriedade(jTFTamanhoPropriedade.getText());
        asso.setAreaUtilizada(jTFAreaUtilizada.getText());
        asso.setIncra(jTFIncra.getText());
        asso.setEnderecoPropriedade(jTFEnderecoProfissao.getText());
        asso.setMunicipioPropriedade(jTFMunicipioProfissao.getText());
        asso.setUfPropriedade(ConversorPersonalizado.convertStringToUF(jCBUfProfissao.getSelectedItem().toString()));
        try {
            asso.setDataPropriedade(ConversorPersonalizado.convertStringToDate(jFTFDataPropria.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(jIFAssociado.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
//  </editor-fold>

        if (asso.getId() <= 0) {
            dao.inserirAlterar(asso);
            JOptionPane.showMessageDialog(rootPane, asso.getNome().toUpperCase() + " cadastrado com sucesso!");
        }
        else {
            dao.alterar(asso);
            JOptionPane.showMessageDialog(rootPane, asso.getNome().toUpperCase() + " alterado com sucesso!");
        }
        
        limparCampos();
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jFTFDataExpedicaoRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDataExpedicaoRGFocusLost
        validateData(jFTFDataExpedicaoRG);
    }//GEN-LAST:event_jFTFDataExpedicaoRGFocusLost

    private void jFTFDataTransferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDataTransferenciaFocusLost
        validateData(jFTFDataTransferencia);
    }//GEN-LAST:event_jFTFDataTransferenciaFocusLost

    private void jFTFDataRecadastramentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDataRecadastramentoFocusLost
        validateData(jFTFDataRecadastramento);
    }//GEN-LAST:event_jFTFDataRecadastramentoFocusLost

    private void jFTFDataPropriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDataPropriaFocusLost
        validateData(jFTFDataPropria);
    }//GEN-LAST:event_jFTFDataPropriaFocusLost

    private void jFTFNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFNascimentoFocusLost
        validateData(jFTFNascimento);
    }//GEN-LAST:event_jFTFNascimentoFocusLost

    private void jFTFDataAdmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDataAdmissaoFocusLost
        validateData(jFTFDataAdmissao);
    }//GEN-LAST:event_jFTFDataAdmissaoFocusLost

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        jdpa = new jDPesquisaAssociado(null, true);
        jdpa.setVisible(true);
        if (jdpa.getAssociado() == null) {
            return;
        }
        
        setAssociado(jdpa.getAssociado());
        populaCampos(associado);
    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jBCarteiraReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCarteiraReportActionPerformed
        Map<String, Object> filtro = new HashMap<String, Object>();
        if (associado == null || associado.getId() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Realize a busca de um associado antes.");
            return;
        }
        
        filtro.put("Id", associado.getId());
        AssociadosReport.buildRelatorio("CarteiraAss", "Teste", filtro);
    }//GEN-LAST:event_jBCarteiraReportActionPerformed

    private void validateData(JFormattedTextField data) {
        String aux = data.getText();
        aux = aux.replaceAll("/", "");
        aux = aux.trim();

        if (!ValidatorUtil.isNullOrEmpty(aux)) {
            if (!ValidatorUtil.isValidDate(data.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Data em formato inválido.");
                data.setText("");
            }
        }
    }

    private boolean validateCamposCadastro() {
        StringBuilder erros = new StringBuilder();
        if (ValidatorUtil.isNullOrEmpty(jTFNome.getText())) {
            erros.append("O Nome não foi preenchido.\n");
        }
        
        String cpf = jFTFCPF.getText().replace(".", "").replace("-", "").trim();
        
        if (ValidatorUtil.isNullOrEmpty(cpf)) {
            erros.append("O CPF não foi preenchido.\n");
        }

        if (erros.length() > 0) {
            JOptionPane.showMessageDialog(rootPane, "O seguintes problemas foram encontrados:\n" + erros.toString());
            return false;
        }

        return true;
    }

    private void populaCampos(Associado asso) {

        jTFMatricula.setText(String.valueOf(asso.getId()));
        jFTFExpedicaoCart.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataExpedicao()));
        jTFMatriculaAnterior.setText(asso.getMatriculaAnterior());
        jFTFDataAdmissao.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataAdmissao()));
        jTFNome.setText(asso.getNome());
        jTFApelido.setText(asso.getApelido());
        jCBSexo.setSelectedItem(asso.getSexo().toString());
        jTFFiliacao.setText(asso.getFiliacaoMae());
        jTFFiliacaoPai.setText(asso.getFiliacaoPai());
        jFTFNascimento.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataNascimento()));
        jTFNaturalidade.setText(asso.getNaturalidade());
        jCBEstadoCivil.setSelectedItem(asso.getEstadoCivil().toString());
        jTFConjuge.setText(asso.getConjuge());
        jTFGrauInstrucao.setText(asso.getGrauInstrucao());
        jTFEnderecoResidencial.setText(asso.getEndereco());
        jTFBairro.setText(asso.getBairro());
        jTFMunicipio.setText(asso.getCidade());
        jCBUF.setSelectedItem(asso.getUf().toString());
        jTFTelefone.setText(asso.getTelefone());
        jTFEmail.setText(asso.getEmail());
        
        jCBRegimeAtividade.setSelectedItem(asso.getRegimeAtividade().toString());
        jCBUfProfissao.setSelectedItem(asso.getUfPropriedade().toString());
        
        jFTFCPF.setText(asso.getCpf());
        jTFRG.setText(asso.getRg());
        jTFOrgExpeditor.setText(asso.getOrgaoExpedidor());
        jFTFDataExpedicaoRG.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataExpedicao()));
        jTFCtps.setText(asso.getCtps());
        jTFSerie.setText(asso.getSerieCtps());
        jTFCertidaoNascimentoCasamento.setText(asso.getCertidaoNascimentoCasamento());
        jTFTituloEleitor.setText(asso.getTituloEleitor());
        jTFZona.setText(asso.getZonaEleitoral());
        jTFSecao.setText(asso.getSecaoEleitoral());
        jTFNumeroBeneficio.setText(asso.getNumeroBeneficio());
        jTFEspecie.setText(asso.getEspecieBeneficio());
        jTFNit.setText(asso.getNit());
        jTFSttr.setText(asso.getTransferidoSTTR());
        jFTFDataTransferencia.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataTransferenciaSTTR()));
        jFTFDataRecadastramento.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataRecadastramento()));
        
        jCBUfProfissao.setSelectedItem(ConversorPersonalizado.convertStringToUF(asso.getUfPropriedade().toString()));
        jCBRegimeAtividade.setSelectedItem(ConversorPersonalizado.convertStringToRegimeAtividade(asso.getRegimeAtividade().toString()));
        jTFProfissao.setText(asso.getProfissao());
        jTFTamanhoPropriedade.setText(asso.getTamanhoPropriedade());
        jTFAreaUtilizada.setText(asso.getAreaUtilizada());
        jTFIncra.setText(asso.getIncra());
        jTFNomeProprietario.setText(asso.getNomeProprietario());
        jTFEnderecoProfissao.setText(asso.getEnderecoPropriedade());
        jTFMunicipioProfissao.setText(asso.getMunicipioPropriedade());
        jFTFDataPropria.setText(ConversorPersonalizado.convertDateToPTBRDate(asso.getDataPropriedade()));
        jTFEmpresaPropriedade.setText(asso.getEmpresaPropriedade());
       

    }

    private void limparCampos() {
        jTFMatricula.setText("");
        jFTFExpedicaoCart.setText("");
        jTFMatriculaAnterior.setText("");
        jFTFDataAdmissao.setText("");
        jTFNome.setText("");
        jTFApelido.setText("");
        jCBSexo.setSelectedIndex(0);
        jTFFiliacao.setText("");
        jTFFiliacaoPai.setText("");
        jFTFNascimento.setText("");
        jTFNaturalidade.setText("");
        jCBEstadoCivil.setSelectedIndex(0);
        jTFConjuge.setText("");
        jTFGrauInstrucao.setText("");
        jTFEnderecoResidencial.setText("");
        jTFBairro.setText("");
        jTFMunicipio.setText("");
        jCBUF.setSelectedIndex(0);
        jTFTelefone.setText("");
        jTFEmail.setText("");

        jFTFCPF.setText("");
        jTFRG.setText("");
        jTFOrgExpeditor.setText("");
        jFTFDataExpedicaoRG.setText("");
        jTFCtps.setText("");
        jTFSerie.setText("");
        jTFCertidaoNascimentoCasamento.setText("");
        jTFTituloEleitor.setText("");
        jTFZona.setText("");
        jTFSecao.setText("");
        jTFNumeroBeneficio.setText("");
        jTFEspecie.setText("");
        jTFNit.setText("");
        jTFSttr.setText("");
        jFTFDataTransferencia.setText("");
        jFTFDataRecadastramento.setText("");
        
        jCBUfProfissao.setSelectedIndex(0);
        jCBRegimeAtividade.setSelectedIndex(0);
        jTFProfissao.setText("");
        jTFTamanhoPropriedade.setText("");
        jTFAreaUtilizada.setText("");
        jTFIncra.setText("");
        jTFNomeProprietario.setText("");
        jTFEnderecoProfissao.setText("");
        jTFMunicipioProfissao.setText("");
        jFTFDataPropria.setText("");
         jTFEmpresaPropriedade.setText("");
        
    }

    private void setFormatos() throws ParseException {
        formatos.getFormatoCPF().install(jFTFCPF);
        formatos.getFormatoDataSimples().install(jFTFNascimento);
        formatos.getFormatoDataSimples().install(jFTFDataExpedicaoRG);
        formatos.getFormatoDataSimples().install(jFTFExpedicaoCart);
        formatos.getFormatoDataSimples().install(jFTFDataAdmissao);
        formatos.getFormatoDataSimples().install(jFTFDataPropria);
        formatos.getFormatoDataSimples().install(jFTFDataRecadastramento);
        formatos.getFormatoDataSimples().install(jFTFDataTransferencia);
    }
    
    private void setAssociado(Associado asso){
        this.associado = asso;
    }

    // <editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCarteiraReport;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBEstadoCivil;
    private javax.swing.JComboBox<String> jCBRegimeAtividade;
    private javax.swing.JComboBox<String> jCBSexo;
    private javax.swing.JComboBox<String> jCBUF;
    private javax.swing.JComboBox<String> jCBUfProfissao;
    private javax.swing.JFormattedTextField jFTFCPF;
    private javax.swing.JFormattedTextField jFTFDataAdmissao;
    private javax.swing.JFormattedTextField jFTFDataExpedicaoRG;
    private javax.swing.JFormattedTextField jFTFDataPropria;
    private javax.swing.JFormattedTextField jFTFDataRecadastramento;
    private javax.swing.JFormattedTextField jFTFDataTransferencia;
    private javax.swing.JFormattedTextField jFTFExpedicaoCart;
    private javax.swing.JFormattedTextField jFTFNascimento;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPDadosPessoais;
    private javax.swing.JPanel jPDadosProfissionais;
    private javax.swing.JPanel jPDependentes;
    private javax.swing.JTabbedPane jPDocumentacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFApelido;
    private javax.swing.JTextField jTFAreaUtilizada;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JTextField jTFCertidaoNascimentoCasamento;
    private javax.swing.JTextField jTFConjuge;
    private javax.swing.JTextField jTFCtps;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEmpresaPropriedade;
    private javax.swing.JTextField jTFEnderecoProfissao;
    private javax.swing.JTextField jTFEnderecoResidencial;
    private javax.swing.JTextField jTFEspecie;
    private javax.swing.JTextField jTFFiliacao;
    private javax.swing.JTextField jTFFiliacaoPai;
    private javax.swing.JTextField jTFGrauInstrucao;
    private javax.swing.JTextField jTFIncra;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFMatriculaAnterior;
    private javax.swing.JTextField jTFMunicipio;
    private javax.swing.JTextField jTFMunicipioProfissao;
    private javax.swing.JTextField jTFNaturalidade;
    private javax.swing.JTextField jTFNit;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNomeProprietario;
    private javax.swing.JTextField jTFNumeroBeneficio;
    private javax.swing.JTextField jTFOrgExpeditor;
    private javax.swing.JTextField jTFProfissao;
    private javax.swing.JTextField jTFRG;
    private javax.swing.JTextField jTFSecao;
    private javax.swing.JTextField jTFSerie;
    private javax.swing.JTextField jTFSttr;
    private javax.swing.JTextField jTFTamanhoPropriedade;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTextField jTFTituloEleitor;
    private javax.swing.JTextField jTFZona;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    private Associado associado = new Associado();
    private Formatos formatos = new Formatos();
    private jDPesquisaAssociado jdpa;
    private Long dd = 0L;

}
